export const dataEn=[
	{id: '1',  lit:"`",   		sec:{inner:'~',  class:['key-sec']},    isFunc:false, code:'192',},
	{id: '2',  lit:'1',   		sec:{inner:'!',  class:['key-sec']},    isFunc:false, code:'49',},
	{id: '3',  lit:'2',   		sec:{inner:'@',  class:['key-sec']},    isFunc:false, code:'50',},
	{id: '4',  lit:'3',   		sec:{inner:'#',  class:['key-sec']},    isFunc:false, code:'51',},
	{id: '5',  lit:'4',   		sec:{inner:'$',  class:['key-sec']},    isFunc:false, code:'52',},
	{id: '6',  lit:'5',   		sec:{inner:'%',  class:['key-sec']},    isFunc:false, code:'53',},
	{id: '7',  lit:'6',   		sec:{inner:'^',  class:['key-sec']},    isFunc:false, code:'54',},
	{id: '8',  lit:'7',   		sec:{inner:'&',  class:['key-sec']},    isFunc:false, code:'55',},
	{id: '9',  lit:'8',   		sec:{inner:'*',  class:['key-sec']},    isFunc:false, code:'56',},
	{id: '10', lit:'9',   		sec:{inner:'(',  class:['key-sec']},    isFunc:false, code:'57',},
	{id: '11', lit:'9',   		sec:{inner:')',  class:['key-sec']},    isFunc:false, code:'58',},
	{id: '12', lit:"-",   		sec:{inner:'_',  class:['key-sec']},    isFunc:false, code:'189',},
	{id: '13', lit:"=",   		sec:{inner:'+',  class:['key-sec']},    isFunc:false, code:'187',},
	{id: '14', lit:'Backspace',  sec:{inner:'',   class:['key-sec']},   	isFunc:true,  code:'8',},
	{id: '15', lit:'TAB', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'9',},
	{id: '16', lit:'Q', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'81',},
	{id: '17', lit:'W', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'87',},
	{id: '18', lit:'E', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'69',},
	{id: '19', lit:'R', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'82',},
	{id: '20', lit:'T', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'84',},
	{id: '21', lit:'Y', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'89',},
	{id: '22', lit:'U', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'85',},
	{id: '23', lit:'I', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'73',},
	{id: '24', lit:'O', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'79',},
	{id: '25', lit:'P', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'80',},
	{id: '26', lit:"[", 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'219'},
	{id: '27', lit:"]", 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'221'},
	{id: '28', lit:"\\",			sec:{inner:'/',  class:['key-sec']},    isFunc:true,  code:'220',},
	{id: '29', lit:'DEL', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'46'},
	{id: '30', lit:'CapsLock', 	sec:{inner:'',   class:['key-sec','tr']},isFunc:true,  code:'20'},
	{id: '31', lit:'A', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'65'},
	{id: '32', lit:'S', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'83'},
	{id: '33', lit:'D', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'68'},
	{id: '34', lit:'F', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'70'},
	{id: '35', lit:'G', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'71'},
	{id: '36', lit:'H', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'72'},
	{id: '37', lit:'J', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'74'},
	{id: '38', lit:'K', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'75'},
	{id: '39', lit:'L', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'76'},
	{id: '40', lit:";", 			sec:{inner:':',  class:['key-sec']},    isFunc:false, code:'186'},
	{id: '41', lit:"'", 			sec:{inner:'"',  class:['key-sec']},    isFunc:false, code:'222'},
	{id: '42', lit:'Enter', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'13'},
	{id: '43', lit:'Shift', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'16'},
	{id: '44', lit:"\\", 		sec:{inner:'|',  class:['key-sec']},    isFunc:false, code:'220'},
	{id: '45', lit:'Z', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'90'},
	{id: '46', lit:'X', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'88'},
	{id: '47', lit:'C', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'67'},
	{id: '48', lit:'V', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'86'},
	{id: '49', lit:'B', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'66'},
	{id: '50', lit:'N', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'78'},
	{id: '51', lit:'M', 			sec:{inner:'',   class:['key-sec']},    isFunc:false, code:'77'},
	{id: '52', lit:"<", 			sec:{inner:',',  class:['key-sec']},    isFunc:false, code:'188'},
	{id: '53', lit:">", 			sec:{inner:'.',  class:['key-sec']},    isFunc:false, code:'190'},
	{id: '54', lit:"/", 			sec:{inner:'?',  class:['key-sec']},    isFunc:false, code:'191'},
	{id: '55', lit:"&#8593", 	sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'38'},
	{id: '56', lit:'Shift', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'16'},
	{id: '57', lit:'Ctrl', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'17'},
	{id: '58', lit:'Win', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'91'},
	{id: '59', lit:'Alt', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'18'},
	{id: '60', lit:'SPACE', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'32'},
	{id: '61', lit:'Alt', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'18'},
	{id: '62', lit:'En', 		sec:{inner:'Ru', class:['key-sec','cg']},  isFunc:true,  code:'92'},
	{id: '62', lit:'Crtrl', 		sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'17'},
	{id: '63', lit:"&#8592;", 	sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'37'},
	{id: '64', lit:"&#8595;", 	sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'40'},
	{id: '65', lit:"&#8594;", 	sec:{inner:'',   class:['key-sec']},    isFunc:true,  code:'39'},
]

export const dataRu=[
	{id:'1',  lit:"`",   	  sec:{inner:'~',  class:['key-sec']},      isFunc:false, code:'192',},
	{id:'2',  lit:'1',   	  sec:{inner:'!',  class:['key-sec']},      isFunc:false, code:'49',},
	{id:'3',  lit:'2',   	  sec:{inner:'@',  class:['key-sec']},      isFunc:false, code:'50',},
	{id:'4',  lit:'3',   	  sec:{inner:'#',  class:['key-sec']},      isFunc:false, code:'51',},
	{id:'5',  lit:'4',   	  sec:{inner:'$',  class:['key-sec']},      isFunc:false, code:'52',},
	{id:'6',  lit:'5',   	  sec:{inner:'%',  class:['key-sec']},      isFunc:false, code:'53',},
	{id:'7',  lit:'6',   	  sec:{inner:'^',  class:['key-sec']},      isFunc:false, code:'54',},
	{id:'8',  lit:'7',   	  sec:{inner:'&',  class:['key-sec']},      isFunc:false, code:'55',},
	{id:'9',  lit:'8',   	  sec:{inner:'*',  class:['key-sec']},      isFunc:false, code:'56',},
	{id:'10', lit:'9',   	  sec:{inner:'(',  class:['key-sec']},      isFunc:false, code:'57',},
	{id:'11', lit:'9',   	  sec:{inner:')',  class:['key-sec']},      isFunc:false, code:'58',},
	{id:'12', lit:"-",   	  sec:{inner:'_',  class:['key-sec']},      isFunc:false, code:'189',},
	{id:'13', lit:"=",   	  sec:{inner:'+',  class:['key-sec']},      isFunc:false, code:'187',},
	{id:'14', lit:'Backspace',sec:{inner:'',   class:['key-sec'],},     isFunc:true,  code:'8',},
	{id:'15', lit:'TAB', 	  sec:{inner:'',   class:['key-sec']},      isFunc:true,  code:'9',},
	{id:'16', lit:"Й", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'81',},
	{id:'17', lit:"Ц", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'87',},
	{id:'18', lit:"У", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'69',},
	{id:'19', lit:"К", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'82',},
	{id:'20', lit:"Е", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'84',},
	{id:'21', lit:"Н", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'89',},
	{id:'22', lit:"Г", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'85',},
	{id:'23', lit:"Ш", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'73',},
	{id:'24', lit:"Щ", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'79',},
	{id:'25', lit:"З", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'80',},
	{id:'26', lit:"Х", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'219'},
	{id:'27', lit:"Ъ", 		  sec:{inner:'',   class:['key-sec']},      isFunc:false, code:'221'},
	{id:'28', lit:"\\",		  sec:{inner:'/',  class:['key-sec']},      isFunc:true,  code:'220',},
	{id:'29', lit:'DEL', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'46'},
	{id:'30', lit:'CapsLock', sec:{inner:'',   class:['key-sec','tr']}, isFunc:true,  code:'20'},
	{id:'31', lit:"Ф", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'65'},
	{id:'32', lit:"Ы", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'83'},
	{id:'33', lit:"В", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'68'},
	{id:'34', lit:"А", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'70'},
	{id:'35', lit:"П", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'71'},
	{id:'36', lit:"Р", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'72'},
	{id:'37', lit:"О", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'74'},
	{id:'38', lit:"Л", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'75'},
	{id:'39', lit:"Д", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'76'},
	{id:'40', lit:"Ж", 		  sec:{inner:':',  class:['key-sec']},		isFunc:false, code:'186'},
	{id:'41', lit:"\\", 	  sec:{inner:'"',  class:['key-sec']},		isFunc:false, code:'222'},
	{id:'42', lit:'Enter', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'13'},
	{id:'43', lit:'Shift', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'16'},
	{id:'44', lit:"\\", 	  sec:{inner:'|',  class:['key-sec']},		isFunc:false, code:'220'},
	{id:'45', lit:"Я", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'90'},
	{id:'46', lit:"Ч", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'88'},
	{id:'47', lit:"С", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'67'},
	{id:'48', lit:"М", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'86'},
	{id:'49', lit:"И", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'66'},
	{id:'50', lit:"Т", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'78'},
	{id:'51', lit:"Ь", 		  sec:{inner:'',   class:['key-sec']}, 		isFunc:false, code:'77'},
	{id:'52', lit:"Б", 		  sec:{inner:',',  class:['key-sec']},		isFunc:false, code:'188'},
	{id:'53', lit:"Ю", 		  sec:{inner:'.',  class:['key-sec']},		isFunc:false, code:'190'},
	{id:'54', lit:".", 		  sec:{inner:',',  class:['key-sec']},		isFunc:false, code:'191'},
	{id:'55', lit:"&#8593",   sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'38'},
	{id:'56', lit:'Shift', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'16'},
	{id:'57', lit:'Ctrl', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'17'},
	{id:'58', lit:'Win', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'91'},
	{id:'59', lit:'Alt', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'18'},
	{id:'60', lit:'SPACE', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'32'},
	{id:'61', lit:'Alt', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'18'},
	{id:'62', lit:'Ru', 	  sec:{inner:'En', class:['key-sec','cg']}, isFunc:true,  code:'92'},
	{id:'62', lit:'Crtrl', 	  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'17'},
	{id:'63', lit:"&#8592;",  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'37'},
	{id:'64', lit:"&#8595;",  sec:{inner:'',   class:['key-sec']}, 		isFunc:true,  code:'40'},
	{id:'65', lit:"&#8594;",  sec:{inner:'',   class:['key-sec']},		isFunc:true,  code:'39'},
	
]
